version: '3.8'

services:
  api:
    container_name: inforce_api
    build: .
    restart: always
    env_file: backend/.env
    command: >
      sh -c "python backend/manage.py migrate --no-input && python backend/manage.py runserver"
    volumes:
     - .:/app
     - uploads_volume:/app/uploads
    depends_on:
     - db

  db:
    container_name: inforce_db
    image: postgres:14.3-alpine
    env_file: backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  uploads_volume:
  postgres_data: